root: true
extends: eslint:recommended

parserOptions:
  ecmaVersion: 8
  sourceType: module
  ecmaFeatures:
    impliedStrict: true

env:
  node: true
  es6: true

plugins:
  - import

rules:
  # Possible Errors
  for-direction: error
  getter-return: error
  no-await-in-loop: error
  # no-extra-parens: off
  no-prototype-builtins: error
  no-template-curly-in-string: error
  valid-jsdoc: error

  # Best Practices
  accessor-pairs: error
  array-callback-return: error
  block-scoped-var: error
  class-methods-use-this: error
  complexity:
    - warn
    - 20
  consistent-return: error
  curly:
    - error
    - multi-line
  default-case: error
  dot-location:
    - error
    - property
  dot-notation:
    - error
    - allowPattern: ^([a-z]+(_[a-z]+)+)|class$
  eqeqeq: error
  guard-for-in: error
  no-alert: error
  no-caller: error
  no-div-regex: error
  no-else-return: error
  no-empty-function: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-floating-decimal: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: error
  no-labels:
    - error
    - allowLoop: true
  no-lone-blocks: error
  no-loop-func: error
  # no-magic-numbers: off
  no-multi-spaces: error
  no-multi-str: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: error
  no-proto: error
  # no-restricted-properties: off
  # no-return-assign: off
  no-return-await: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-return: error
  # no-void: off
  no-warning-comments:
    - warn
    - location: anywhere
  no-with: error
  prefer-promise-reject-errors: error
  radix: error
  require-await: error
  vars-on-top: error
  wrap-iife: error
  yoda: error

  # Strict Mode
  strict: error

  # Variables
  init-declarations: error
  no-catch-shadow: error
  no-label-var: error
  # no-restricted-globals: off
  # no-shadow: off
  no-shadow-restricted-names: error
  no-undef-init: error
  no-undefined: error
  no-unused-vars:
    - error
    - args: none
  no-use-before-define:
    - error
    - nofunc

  # Node.js and CommonJS
  callback-return: error
  # global-require: off
  handle-callback-err:
    - error
    - ^(err|error|.+Error)$
  no-buffer-constructor: error
  no-mixed-requires: error
  no-new-require: error
  no-path-concat: error
  # no-process-env: off
  no-process-exit: error
  # no-restricted-modules: off
  no-sync: error

  # Stylistic Issues
  # array-bracket-newline: off
  array-bracket-spacing: error
  # array-element-newline: off
  block-spacing: error
  brace-style: error
  camelcase: error
  # capitalized-comments: off
  comma-dangle:
    - error
    - always-multiline
  comma-spacing: error
  comma-style: error
  computed-property-spacing: error
  consistent-this: error
  eol-last: error
  func-call-spacing: error
  func-name-matching: error
  func-names:
    - error
    - as-needed
  # func-style: off
  # function-paren-newline: off
  # id-blacklist: off
  # id-length: off
  # id-match: off
  # implicit-arrow-linebreak: off
  indent: error
  jsx-quotes: error
  key-spacing: error
  keyword-spacing: error
  # line-comment-position: off
  linebreak-style: error
  lines-around-comment:
    - error
    - allowBlockStart: true
      ignorePattern: webpackChunkName
  max-depth:
    - warn
    - max: 5
  max-len:
    - warn
    - code: 150
      ignoreTrailingComments: true
      ignoreUrls: true
  max-lines:
    - warn
    - max: 500
  max-nested-callbacks:
    - warn
    - max: 5
  max-params:
    - warn
    - max: 10
  max-statements:
    - warn
    - max: 25
  max-statements-per-line: error
  # multiline-comment-style: off
  # multiline-ternary: off
  new-cap: error
  new-parens: error
  newline-per-chained-call:
    - error
    - ignoreChainWithDepth: 3
  no-array-constructor: error
  no-bitwise: error
  # no-continue: off
  # no-inline-comments: off
  no-lonely-if: error
  no-mixed-operators: error
  no-multi-assign: error
  no-multiple-empty-lines: error
  no-negated-condition: error
  no-nested-ternary: error
  no-new-object: error
  # no-plusplus: off
  # no-restricted-syntax: off
  no-tabs: error
  # no-ternary: off
  no-trailing-spaces: error
  no-underscore-dangle:
    - error
    - allowAfterThis: true
      allow:
        - __WebpackPolyfillInjector
        - __WebpackPolyfillInjectorInWatchRun
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  nonblock-statement-body-position: error
  # object-curly-newline: off
  object-curly-spacing: error
  object-property-newline:
    - error
    - allowMultiplePropertiesPerLine: true
  # one-var: off
  one-var-declaration-per-line: error
  operator-assignment: error
  operator-linebreak: error
  padded-blocks:
    - error
    - never
  # padding-line-between-statements: off
  quote-props:
    - error
    - consistent-as-needed
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  # require-jsdoc: off
  semi: error
  semi-spacing: error
  semi-style: error
  # sort-keys: off
  # sort-vars: off
  space-before-blocks: error
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment:
    - error
    - always
    - line:
        exceptions:
          - '-'
      block:
        markers:
          - '!'
        balanced: true
  switch-colon-spacing: error
  template-tag-spacing: error
  unicode-bom: error
  wrap-regex: error

  # ECMAScript 6
  arrow-body-style: error
  arrow-parens:
    - error
    - as-needed
    - requireForBlockBody: true
  arrow-spacing: error
  generator-star-spacing: error
  no-confusing-arrow:
    - error
    - allowParens: true
  no-duplicate-imports: error
  # no-restricted-imports: off
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-rename: error
  no-var: error
  object-shorthand:
    - error
    - always
    - avoidQuotes: true
      avoidExplicitReturnArrows: true
  prefer-arrow-callback:
    - error
    - allowNamedFunctions: true
      allowUnboundThis: true
  prefer-const: error
  # prefer-destructuring: off
  prefer-numeric-literals: error
  prefer-rest-params: error
  prefer-spread: error
  # prefer-template: off
  rest-spread-spacing: error
  # sort-imports: off
  symbol-description: error
  template-curly-spacing: error
  yield-star-spacing: error


  ##############################################################################
  #                            eslint-plugin-import                            #
  ##############################################################################
  # Static analysis
  import/no-unresolved:
    - error
    - commonjs: true
  import/named: error
  import/default: error
  import/namespace: error
  # import/no-restricted-paths: off
  import/no-absolute-path: error
  import/no-dynamic-require: error
  # import/no-internal-modules: off
  import/no-webpack-loader-syntax: error

  # Helpful warnings
  import/export: error
  import/no-named-as-default: error
  import/no-named-as-default-member: error
  import/no-deprecated: warn
  import/no-extraneous-dependencies: error
  import/no-mutable-exports: error

  # Module systems
  # import/unambiguous: off
  # import/no-commonjs: off
  import/no-amd: error
  # import/no-nodejs-modules: off

  # Style guide
  import/first: error
  import/exports-last: error
  import/no-duplicates: error
  import/no-namespace: error
  # import/extensions:
  #   - error
  #   - ignorePackages
  import/order: error
  import/newline-after-import: error
  import/prefer-default-export: error
  import/max-dependencies:
    - warn
    - max: 10
  import/no-unassigned-import: error
  import/no-named-default: error
  # import/no-anonymous-default-export: off
